---
title: "CDC"
author: "Graham Casey Gibson"
date: "1/1/2020"
output: pdf_document
---

Utility function to get data for a specific epiweek, specific issue date, and specific region. 

```{r}
score_dist <- function(dist,truth){
  return (sum(round(dist,1) ==  round(truth,1))/length(dist))
}
```
```{r}
predownload_data <- function(){
  data_obj <- list()
  data_obj_idx <- 1
  for (region in c("nat",paste0("hhs",1:10))){
    req <- curl_fetch_memory(paste0("https://delphi.midas.cs.cmu.edu/epidata/api.php?source=fluview&regions=",region,"&epiweeks=201240-201920"))
    req_json <- jsonlite::prettify(rawToChar(req$content))
    data_obj[[data_obj_idx]] <- jsonlite::fromJSON(req_json)$epidata
    data_obj_idx <- data_obj_idx +1
  }
  total_data <- do.call(rbind, data_obj)
  saveRDS(total_data,"data.RDS")
}


get_ili_for_epiweek_and_issue <- function(start_epiweek,end_epiweek,region){
  total_data <- readRDS("data.RDS")
  return (total_data[total_data$region == region & total_data$epiweek <= end_epiweek & total_data$epiweek >= start_epiweek ,]$wili)
  
}


```
```{r}

plot_predictive_dist <- function(pred_dist,truth,test_idx,method,previous_point,location){
  p <-ggplot(data=data.frame(x = pred_dist),aes(x=x)) + geom_histogram()+geom_vline(xintercept =truth ) +xlim(0,10) + geom_vline(xintercept = previous_point,col='blue')
      ggsave(filename = paste0(location,"-",method,"-",test_idx),plot = p,device = "png")
}

plot_data_till_time_t <- function(data){
  p <-ggplot(data=data.frame(x = 1:length(data),y=data),aes(x=x,y=y)) + geom_line()
      ggsave(filename = paste0("data-",test_idx),plot = p,device = "png")
}
```

Code for data set-up and evaluation given a specific region.

```{r}
library(quantmod)
library(pander)
library(cdcfluview)
library(sarimaTD)
library(cdcfluutils)
library(ggplot2)

## declare region to be analyzed 
region_str <- c("National",paste0("Region ",1:10))
region_abbrv <- c("nat",paste0("hhs",1:10))

kcde_score_df <- matrix(NA,nrow=55*68,ncol=3)
sarima_score_df <- matrix(NA,nrow=55*68,ncol=3)
h <- 2
score_idx <-1
for (location in 1:length(region_str)){
    region_str_local <- region_str[location]
    region_abbrv_local <- region_abbrv[location]
    train_data <- get_ili_for_epiweek_and_issue("201240","201740",region_abbrv_local)
    
    test_data <- get_ili_for_epiweek_and_issue("201740","201820",region_abbrv_local)
    
     
    ## GET SARIMA FIT
     
     sarima_fit_bc_transform <- fit_sarima(
      y = train_data,
      ts_frequency = 52,
      transformation = "box-cox",
      seasonal_difference = T)
    #sarima_fit_bc_transform <- Arima(train_data,order = c(1,0,0))
    #sarima_fit_bc_transform <- auto.arima(train_data)
    print (sarima_fit_bc_transform)

    rbf_fit_ret_list <- fit_rbf_jags(train_data,num_lags = 1,h = 1)
    rbf_fit <- rbf_fit_ret_list[[1]]
    rbf_fit2 <- rbf_fit_ret_list[[2]]
    rbf_fit3 <- rbf_fit_ret_list[[3]]

    rbf_var <- rbf_fit_ret_list[[4]]
    ## GET KCDE FIT
    #par <- fit_and_return_par(diff(train_data))

    test_epiweeks <- c(201740:201752,paste0(2018,"0",1:9),201810:201818)
     
    
    for (test_idx  in 1:(length(test_epiweeks)-h)){
      epiweek_cutoff <- test_epiweeks[test_idx]
      truth <- tail(get_ili_for_epiweek_and_issue(test_epiweeks[test_idx + h ],test_epiweeks[test_idx + h],region_abbrv_local),1)

      plot_data_till_time_t(c(tail(train_data,10),test_data[1:test_idx],truth))      
      
      
      ### GET SARIMA PREDS
       sarima_pred_dist<- simulate(
        object = sarima_fit_bc_transform,
        nsim = 10000,
        seed = 1,
        newdata = c(train_data,test_data[1:test_idx]),
        h = h
      )
      sarima_pred_dist <- sarima_pred_dist[,2]
      
      sarima_pred_dist <- sarima_pred_dist[!is.na(sarima_pred_dist)]
      sarima_pred_dist <- sarima_pred_dist[!is.nan(sarima_pred_dist)]

      ### GET KCDE 
      if (h==1){
        kcde_pred_dist <-stats::predict(rbf_fit,newdata=test_idx,h=1) +
        stats::predict(rbf_fit2,newdata=test_idx) + logit(test_data[test_idx]/100)
      } else if(h==2){
        kcde_pred_dist <-rbf_fit[test_idx] + 
          rbf_fit[test_idx]+
           logit(test_data[test_idx]/100)
      }
      kcde_pred_dist <- inv.logit(rnorm(10000,kcde_pred_dist,2*.1))*100

      
      sarima_score_df[score_idx,] <- c(region_abbrv_local,test_idx,score_dist( sarima_pred_dist,truth) )
      kcde_score_df[score_idx,] <- c(region_abbrv_local,test_idx,score_dist( kcde_pred_dist,truth) )
      plot_predictive_dist(pred_dist =sarima_pred_dist,truth = truth,test_idx = test_idx,method="sarima" ,previous_point = tail(test_data,1),location=location)
      plot_predictive_dist(pred_dist =kcde_pred_dist,truth=truth,test_idx = test_idx,method="kcde",previous_point = tail(test_data,1),location=location) 
      ### SCORE DATAFRAME COUNTER
      score_idx <- score_idx +1
      
        
      
    
    }
}

kcde_score_df <- data.frame(kcde_score_df)
colnames(kcde_score_df) <- c("region","epiweek","kcde_ls")
saveRDS(object = kcde_score_df,file="kcde_score_df_2016-2017_h_2")

sarima_score_df <- data.frame(sarima_score_df)
colnames(sarima_score_df) <- c("region","epiweek","sarima_ls")
saveRDS(object = sarima_score_df,file="sarima_score_df_2016-2017_h_2")


print (mean(as.numeric(as.character(kcde_score_df$kcde_ls)),na.rm=T))
print (mean(as.numeric(as.character(sarima_score_df$sarima_ls)),na.rm=T))

```


```{r}
kcde_score_df <- readRDS("kcde_score_df_2016-2017_h_2")
sarima_score_df <- readRDS("sarima_score_df_2016-2017_h_2")
kcde_score_df <- kcde_score_df[complete.cases(kcde_score_df),]
sarima_score_df <- sarima_score_df[complete.cases(sarima_score_df),]

total_score_df <- merge(kcde_score_df,sarima_score_df)
total_score_df$sarima_ls <- as.numeric(as.character(total_score_df$sarima_ls))
total_score_df$kcde_ls <- as.numeric(as.character(total_score_df$kcde_ls))


library(ggplot2)
library(dplyr)
p <- ggplot(total_score_df[total_score_df$epiweek %in% 4:30,] %>% group_by(region) %>% summarize(kcde_ls=mean(kcde_ls),sarima_ls=mean(sarima_ls)),aes(x=region,y=sarima_ls,col='sarimaTD')) + geom_point() +
  geom_point(aes(x=region,y=kcde_ls,col='KCDE')) + facet_grid(~region)
ggsave(filename = "regional_results",plot = p,device = "png")

```





```{r}
#library(reticulate)
#use_python("/Users/gcgibson/anaconda/bin/python2.7")
#reticulate::source_python("test.py")
fit_rbf <- function(ts_local,num_lags,h){
    ts_local <- logit(ts_local/100)

    if (TRUE){
        
        diff_data <- data.frame(x=rep(1:52,length.out=length(diff(ts_local))),y=diff(ts_local))
        diff_data_2 <- data.frame(x=rep(1:52,length.out=length(diff(ts_local,differences=2))),y=diff(ts_local,differences=2))
        diff_data_3 <- data.frame(x=rep(1:52,length.out=length(diff(ts_local,differences=3))),y=diff(ts_local,differences=3))
        loessMod10 <- loess(y ~ x, data=diff_data, span=0.10) 
        loessMod102 <- loess(y ~ x, data=diff_data_2, span=0.10) 
        loessMod103 <- loess(y ~ x, data=diff_data_3, span=0.80) 

        
        diff_data$factor_x <- as.factor(diff_data$x)
        vars <- diff_data %>% group_by(factor_x) %>% summarise(var=var(y))
        ret_list <- list()
      
        ret_list[[1]] <- loessMod10
        ret_list[[2]] <- loessMod102
        ret_list[[3]] <- loessMod103

        ret_list[[4]] <- sqrt(median(vars$var))
    }
   
  
  
    return(ret_list)
}

library(R2jags)
library(rjags)

fit_rbf_jags <- function(ts_local,num_lags,h){
    ts_local <- logit(ts_local/100)

  
        
        
    diff_data <- data.frame(x=rep(1:52,length.out=6*52),y=c(diff(ts_local),rep(NA,length.out=6*52-length(diff(ts_local)))))
        diff_data_2 <- data.frame(x=rep(1:52,length.out=length(diff(ts_local,differences=2))),y=diff(ts_local,differences=2))
        diff_data_3 <- data.frame(x=rep(1:52,length.out=length(diff(ts_local,differences=3))),y=diff(ts_local,differences=3))
        
        
        model.loc=("ss_model.txt")
          jagsscript = cat("
          model {  
             # priors on parameters
             mu ~ dnorm(0, 0.01); 
             tau.pro ~ dgamma(0.001,0.001); 
             sd.q <- 1/sqrt(tau.pro);
             tau.obs ~ dgamma(0.001,0.001);
             sd.r <- 1/sqrt(tau.obs); 
             phi ~ dnorm(0,1);
             phi2 ~ dnorm(0,1);

             
            for (s in 1:5){
             X[1,s] <- mu;
             predY[1,s] <- X[1,s];
             Y[1,s] ~ dnorm(X[1,s], tau.obs);
            }
            Z[1] <- mu;

            for (i in 2:52){
               Z[i] ~ dnorm(phi2*Z[i-1],tau.pro);
            }
            for (s in 1:5){
               for(i in 2:52) {
                  predX[i,s] <- phi*X[i-1,s]; 
                  X[i,s] ~ dnorm(predX[i,s],tau.pro); # Process variation
                  predY[i,s] <- X[i,s];
                  Y[i,s] ~ dnorm(X[i,s] + Z[i], tau.obs); # Observation variation
               }
            }
          }  
          ",file=model.loc)
        
        jags.data = list("Y"=t(matrix(diff_data$y,ncol=52)))
        jags.params=c("sd.q","sd.r","predY","mu","Z")
        mod_ss = jags(jags.data, parameters.to.save=jags.params, model.file=model.loc, n.chains = 3, 
        n.burnin=5000, n.thin=1, n.iter=10000, DIC=TRUE)  
       
        #colMeans(mod_ss$BUGSoutput$sims.matrix[,paste0("Z[",1:52,"]")])
        ret_list <- list()
        ret_list[[1]] <- colMeans(mod_ss$BUGSoutput$sims.matrix[,paste0("Z[",1:52,"]")])
        ret_list[[2]] <- 1
        ret_list[[3]] <- 1

        ret_list[[4]] <- 1
    
   
  
  
    return(ret_list)
}


#debug(fit_and_predict_rbf)

#print (fit_and_predict_rbf(1:101,4,1))
```

